In [64]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split,KFold
from sklearn.model_selection import cross_val_score,GridSearchCV
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.metrics import mean_squared_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
import xgboost as xgb

In [2]:
df=pd.read_csv('/Users/ashish/Desktop/House-Price-Prediction/final_housing.csv')

In [3]:
df

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,zipcode,lat,long,renovated
0,0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,98178,47.5112,-122.257,0
1,1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,98125,47.7210,-122.319,1
2,2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,98028,47.7379,-122.233,0
3,3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,98136,47.5208,-122.393,0
4,4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,98074,47.6168,-122.045,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,98103,47.6993,-122.346,0
21609,21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,98146,47.5107,-122.362,0
21610,21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,98144,47.5944,-122.299,0
21611,21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,98027,47.5345,-122.069,0
21612,21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,98144,47.5941,-122.299,0

In [4]:
df=df.drop(columns=['Unnamed: 0','zipcode','condition'])

In [5]:
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,grade,sqft_above,sqft_basement,yr_built,lat,long,renovated
0,221900.0,3,1.00,1180,5650,1.0,0,0,7,1180,0,1955,47.5112,-122.257,0
1,538000.0,3,2.25,2570,7242,2.0,0,0,7,2170,400,1951,47.7210,-122.319,1
2,180000.0,2,1.00,770,10000,1.0,0,0,6,770,0,1933,47.7379,-122.233,0
3,604000.0,4,3.00,1960,5000,1.0,0,0,7,1050,910,1965,47.5208,-122.393,0
4,510000.0,3,2.00,1680,8080,1.0,0,0,8,1680,0,1987,47.6168,-122.045,0

In [55]:
X=df.iloc[:,1:]
y=df.iloc[:,0]

In [7]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [8]:
reg=LinearRegression()

In [9]:
reg.fit(X_train,y_train)

LinearRegression()

In [10]:
reg.coef_

array([-3.18345355e+04,  4.79081740e+04,  1.13592950e+02, -9.60059053e-02,
       -4.27209745e+03,  5.65211747e+05,  5.30197962e+04,  1.01121155e+05,
        7.30684379e+01,  4.05245121e+01, -2.81543715e+03,  5.49683498e+05,
       -7.79021491e+04,  2.53457417e+04])

In [11]:
reg.intercept_

-30731966.411432505

In [12]:
y_pred=reg.predict(X_test)

In [13]:
reg.score(X_test,y_test)

0.6908059557365152

In [14]:
y_pred

array([ 435998.88526391,  731307.2549672 , 1210120.93782059, ...,
        383431.92695381,  584186.35828257,  402763.17404   ])

In [15]:
y_test

735       365000.0
2830      865000.0
4106     1038000.0
16218    1490000.0
19964     711000.0
           ...
13674     338000.0
20377     673000.0
8805      285000.0
10168     605000.0
2522      356500.0
Name: price, Length: 4323, dtype: float64

In [16]:
mean_squared_error(y_test,y_pred)

46742939061.15462

In [17]:
#using ridge regression to introduce penalty to the variables

In [18]:
ridge=Ridge(alpha=1)

In [19]:
ridge.fit(X_train,y_train)

Ridge(alpha=1)

In [20]:
ridge.coef_

array([-3.18774878e+04,  4.79135627e+04,  1.13614230e+02, -9.65934088e-02,
       -4.16916226e+03,  5.59783029e+05,  5.32259897e+04,  1.01157635e+05,
        7.30375823e+01,  4.05773677e+01, -2.81839762e+03,  5.47792795e+05,
       -7.77045931e+04,  2.53739451e+04])

In [21]:
ridge.intercept_

-30612370.454566155

In [22]:
ridge.score(X_test,y_test)

0.6907434456402124

In [59]:
rand_forest=RandomForestRegressor(max_depth=13,n_estimators=200)

In [60]:
kf = KFold(n_splits=5)
kf.get_n_splits(X)
print(kf)
scores=[]

KFold(n_splits=5, random_state=None, shuffle=False)

In [61]:
for i, (train_index, test_index) in enumerate(kf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    rand_forest.fit(X_train, y_train)
    scores.append(rand_forest.score(X_test, y_test))

In [62]:
print(np.mean(scores))

0.8714648013482698

In [35]:
print(np.mean(cross_val_score(rand_forest, X, y, cv=5)))

0.8603590066402702

In [30]:
#using grid search to find the best value for random_forst such as n_estimators, max_depth

In [38]:
grid ={"max_depth":list(np.arange(10,14)),"n_estimators":[100,200]}

In [39]:
ran_for=RandomForestRegressor()

In [40]:
knn_cv=GridSearchCV(ran_for,grid,cv=10)

In [41]:
knn_cv.fit(X,y)

GridSearchCV(cv=10, estimator=RandomForestRegressor(),
             param_grid={'max_depth': [10, 11, 12, 13],
                         'n_estimators': [100, 200]})

In [43]:
print("tuned hyperparameter K:",knn_cv.best_params_)
print("tuned parameters: (best score):",knn_cv.best_score_)

tuned hyperparameter K: {'max_depth': 13, 'n_estimators': 200}
tuned parameters: (best score): 0.8730465943803569

In [63]:
#using XG-boost for regression

In [74]:
reg = xgb.XGBRegressor(
    tree_method="hist",
    eval_metric=mean_squared_error,
)

In [75]:
reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False,
             eval_metric=<function mean_squared_error at 0x143db1440>,
             feature_types=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=13,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [76]:
reg.score(X_test,y_test)

0.8507012468424191

In [77]:
dir(xgb)

['Booster',
 'DMatrix',
 'DataIter',
 'DeviceQuantileDMatrix',
 'QuantileDMatrix',
 'RabitTracker',
 'XGBClassifier',
 'XGBModel',
 'XGBRFClassifier',
 'XGBRFRegressor',
 'XGBRanker',
 'XGBRegressor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_py_version',
 '_typing',
 'build_info',
 'callback',
 'collective',
 'compat',
 'config',
 'config_context',
 'core',
 'cv',
 'dask',
 'data',
 'get_config',
 'libpath',
 'plot_importance',
 'plot_tree',
 'plotting',
 'set_config',
 'sklearn',
 'to_graphviz',
 'tracker',
 'train',
 'training']