In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split,KFold,cross_val_score,GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.metrics import mean_squared_error,mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
import xgboost as xgb
from mlxtend.evaluate import bias_variance_decomp

In [35]:
df=pd.read_csv('/Users/ashish/Desktop/House-Price-Prediction/final_housing.csv')

In [36]:
df

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,zipcode,lat,long,renovated
0,0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,98178,47.5112,-122.257,0
1,1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,98125,47.7210,-122.319,1
2,2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,98028,47.7379,-122.233,0
3,3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,98136,47.5208,-122.393,0
4,4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,98074,47.6168,-122.045,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21608,21608,360000.0,3,2.50,1530,1131,3.0,0,0,3,8,1530,0,2009,98103,47.6993,-122.346,0
21609,21609,400000.0,4,2.50,2310,5813,2.0,0,0,3,8,2310,0,2014,98146,47.5107,-122.362,0
21610,21610,402101.0,2,0.75,1020,1350,2.0,0,0,3,7,1020,0,2009,98144,47.5944,-122.299,0
21611,21611,400000.0,3,2.50,1600,2388,2.0,0,0,3,8,1600,0,2004,98027,47.5345,-122.069,0
21612,21612,325000.0,2,0.75,1020,1076,2.0,0,0,3,7,1020,0,2008,98144,47.5941,-122.299,0

In [37]:
df=df.drop(columns=['Unnamed: 0'])

In [38]:
df_encoded = pd.get_dummies(df, columns=['zipcode'],dtype=int)

In [39]:
df_encoded.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,...,zipcode_98146,zipcode_98148,zipcode_98155,zipcode_98166,zipcode_98168,zipcode_98177,zipcode_98178,zipcode_98188,zipcode_98198,zipcode_98199
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,...,0,0,0,0,0,0,1,0,0,0
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,...,0,0,0,0,0,0,0,0,0,0
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,...,0,0,0,0,0,0,0,0,0,0
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,...,0,0,0,0,0,0,0,0,0,0
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,...,0,0,0,0,0,0,0,0,0,0

In [40]:
X=df_encoded.iloc[:,1:].to_numpy()
y=df_encoded.iloc[:,0].to_numpy()

In [41]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [42]:
reg=LinearRegression()

In [43]:
reg.fit(X_train,y_train)

LinearRegression()

In [44]:
reg.coef_

array([-2.66849110e+04,  2.72602672e+04, -1.38896712e+11,  2.00438895e-01,
       -4.78529935e+04,  6.42284759e+05,  5.68447203e+04,  2.35761100e+04,
        5.74569703e+04,  1.38896712e+11,  1.38896712e+11, -7.70708714e+02,
        2.15360562e+05, -1.28681241e+05,  3.22730138e+04,  3.68584398e+06,
        3.71617583e+06,  3.66114244e+06,  4.38923137e+06,  3.93810745e+06,
        3.92994216e+06,  3.88250513e+06,  3.88869838e+06,  3.78401852e+06,
        3.72417213e+06,  3.76347357e+06,  3.72885810e+06,  3.73427694e+06,
        3.63610796e+06,  3.82856421e+06,  3.84110164e+06,  3.71638226e+06,
        3.88180781e+06,  3.69216919e+06,  3.69122210e+06,  3.67333009e+06,
        3.98356410e+06,  3.80661274e+06,  3.74186645e+06,  4.89874668e+06,
        4.16323826e+06,  3.69492763e+06,  3.81183009e+06,  3.85825176e+06,
        3.83503408e+06,  3.71152398e+06,  3.75137366e+06,  3.70250893e+06,
        3.74761855e+06,  3.77966120e+06,  3.60107068e+06,  3.76153683e+06,
        3.82342516e+06,  3.82605516e+06,  3.73672941e+06,  3.67630639e+06,
        4.13841774e+06,  3.94084034e+06,  4.07229196e+06,  3.77592348e+06,
        3.93955819e+06,  3.75953754e+06,  4.10597724e+06,  4.24273582e+06,
        3.93671543e+06,  3.90961914e+06,  3.90773087e+06,  3.80682785e+06,
        4.08910090e+06,  3.95866069e+06,  3.79951547e+06,  3.81686577e+06,
        3.75508120e+06,  3.87169425e+06,  3.89685016e+06,  3.73954791e+06,
        3.73034954e+06,  3.72983344e+06,  3.71069736e+06,  3.72132826e+06,
        3.80168144e+06,  3.69086661e+06,  3.69678457e+06,  3.66562333e+06,
        3.97720994e+06])

In [45]:
reg.intercept_

-28593098.514575835

In [46]:
y_pred=reg.predict(X_test)

In [47]:
reg.score(X_test,y_test)

0.8065795873459

In [48]:
y_pred

array([ 367832.92292416,  828527.01667416, 1239055.17292416, ...,
        377308.92292416,  668594.67292416,  382305.04792416])

In [49]:
y_test

array([ 365000.,  865000., 1038000., ...,  285000.,  605000.,  356500.])

In [50]:
mean_squared_error(y_test,y_pred)

29240662068.411346

In [52]:
avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        reg, X_train, y_train, X_test, y_test, 
        loss='mse',
        random_seed=123)

In [53]:
print('Average expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

Average expected loss: 29479798430.817
Average bias: 29227767087.880
Average variance: 252031342.937

In [44]:
#using ridge regression to introduce penalty to the variables

In [45]:
ridge=Ridge(alpha=1)

In [46]:
ridge.fit(X_train,y_train)

Ridge(alpha=1)

In [47]:
ridge.coef_

array([-2.67819912e+04,  2.74739711e+04,  1.13583733e+02,  1.96488456e-01,
       -4.72761580e+04,  6.35298119e+05,  5.70493262e+04,  2.35948636e+04,
        5.78499154e+04,  9.78421222e+01,  1.57424855e+01, -7.91215433e+02,
        2.79198557e+05, -1.31878626e+05,  3.23428617e+04, -1.38781490e+05,
       -1.08115302e+05, -1.63976083e+05,  5.41696866e+05,  9.26927384e+04,
        8.83217934e+04,  3.78682330e+04,  4.41682866e+04, -4.11492409e+04,
       -1.28667647e+05, -8.23009401e+04, -1.21745198e+05, -8.32510361e+04,
       -1.88934441e+05, -1.10965531e+04,  2.72176380e+03, -1.36847223e+05,
        4.09467617e+04, -1.35861843e+05, -1.39151737e+05, -1.54566503e+05,
        1.34265165e+05, -4.46283329e+04, -8.61245047e+04,  1.02609036e+06,
        3.19889449e+05, -1.32984057e+05, -2.19651707e+04,  9.47979225e+03,
       -1.28658624e+04, -1.22503328e+05, -8.61502317e+04, -1.30702966e+05,
       -8.86773744e+04, -5.82828128e+04, -2.27906436e+05, -9.12147886e+04,
       -2.14552766e+04, -1.63664588e+04, -1.15348783e+05, -1.47488868e+05,
        2.87557284e+05,  9.08934238e+04,  2.21956699e+05, -6.39766611e+04,
        8.97052221e+04, -8.10362188e+04,  2.55445982e+05,  3.93727408e+05,
        8.64271006e+04,  6.59462159e+04,  5.71517457e+04, -3.37444779e+04,
        2.39441512e+05,  1.12518471e+05, -5.19862919e+04, -2.41859232e+04,
       -9.75645054e+04,  3.06188969e+04,  5.28438376e+04, -9.78815933e+04,
       -1.00742615e+05, -1.23765383e+05, -1.23607790e+05, -1.15039224e+05,
       -5.19992134e+04, -1.45732714e+05, -1.36155321e+05, -1.64290360e+05,
        1.28443774e+05])

In [48]:
ridge.intercept_

-28141962.240667816

In [49]:
ridge.score(X_test,y_test)

0.8063465003234253

In [54]:
rand_forest=RandomForestRegressor(max_depth=13,n_estimators=200)

In [ ]:
avg_expected_loss, avg_bias, avg_var = bias_variance_decomp(
        rand_forest, X_train, y_train, X_test, y_test, 
        loss='mse',
        random_seed=123)

In [ ]:
print('Average expected loss: %.3f' % avg_expected_loss)
print('Average bias: %.3f' % avg_bias)
print('Average variance: %.3f' % avg_var)

In [51]:
kf = KFold(n_splits=5)
kf.get_n_splits(X)
print(kf)
scores=[]

KFold(n_splits=5, random_state=None, shuffle=False)

In [52]:
for i, (train_index, test_index) in enumerate(kf.split(X)):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    rand_forest.fit(X_train, y_train)
    scores.append(rand_forest.score(X_test, y_test))

In [53]:
print(np.mean(scores))

0.8706090172968217

In [32]:
print(np.mean(cross_val_score(rand_forest, X, y, cv=5)))

0.8712430307397782

In [30]:
#using grid search to find the best value for random_forst such as n_estimators, max_depth

In [49]:
grid ={"max_depth":list(np.arange(10,14)),"n_estimators":[100,200]}

In [50]:
ran_for=RandomForestRegressor()

In [51]:
knn_cv=GridSearchCV(ran_for,grid,cv=5)

In [ ]:
knn_cv.fit(X,y)

In [ ]:
print("tuned hyperparameter K:",knn_cv.best_params_)
print("tuned parameters: (best score):",knn_cv.best_score_)

In [63]:
#using XG-boost for regression

In [54]:
reg = xgb.XGBRegressor(
    tree_method="exact",
    eval_metric=mean_absolute_error,
    max_depth=13,
    n_estimators=200,               # Randomly sample 80% of rows
    colsample_bytree=1.0,
    subsample=1.0 
)

In [55]:
reg.fit(X_train, y_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=1.0, device=None, early_stopping_rounds=None,
             enable_categorical=False,
             eval_metric=<function mean_absolute_error at 0x1494e4180>,
             feature_types=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=13,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=200,
             n_jobs=None, num_parallel_tree=None, random_state=None, ...)

In [56]:
reg.score(X_test,y_test)

0.8599717460505856